spring.application.name=postpaid-invoice-service

spring.datasource.url=jdbc:mysql://localhost:3306/NewBillingSystem

spring.datasource.username=root

spring.datasource.password=qwertyuiop

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true